services:
  postgres:
    image: postgres:18
    container_name: bankofcli-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankofcli
      POSTGRES_USER: bankofcli_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - bankofcli_pgdata:/var/lib/postgresql

volumes:
  bankofcli_pgdata: